name: Robot + Appium

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_api:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das depedências do Projeto
          pip install robotframework
          pip install --upgrade robotframework-appiumlibrary

      - name: Run Robot Framework tests
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        run: |
          echo Executando os testes de API do Robot
          robot -d ./logs/ tests
    
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: results/